global ProblemSettings;
ProblemSettings.CostFunction=CostFunction;
ProblemSettings.nVar=nVar;
ProblemSettings.VarSize=VarSize;
ProblemSettings.VarMin=VarMin;
ProblemSettings.VarMax=VarMax;
ProblemSettings.Orbitmin=Orbitmin;
ProblemSettings.Orbitmax=Orbitmax;
global SGOSettings;
SGOSettings.MaxPerigee=MaxPerigee;
SGOSettings.nPop=nPop;
SGOSettings.nRock=nRock;
SGOSettings.nRubble=nRubble;
SGOSettings.alpha=alpha;
SGOSettings.pOrbitChange=pOrbitChange;
SGOSettings.mu=mu;
SGOSettings.zeta=zeta;
SGOSettings.Jupiter=Jupiter;
SGOSettings.Saturn=Saturn;
SGOSettings.Uranus=Uranus;
SGOSettings.Neptune=Neptune;

